# CF Dashboards
- type: replace
  path: /instance_groups/name=grafana/jobs/-
  value:
    name: cloudfoundry_custom_dashboards
    release: prometheus-extra-dashboards

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=Cloudfundry?/files/-
  value: /var/vcap/jobs/cloudfoundry_custom_dashboards/*.json
